# Generated by Django 3.2 on 2024-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=12)),
                ('sn', models.CharField(max_length=150)),
                ('sy', models.IntegerField(default=1)),
                ('sb', models.CharField(choices=[('0', '-- Select Branch --'), ('1', 'Computer Science and Engineering'), ('2', 'Artificial Intelligence/Machine Learning'), ('3', 'Others')], default='0', max_length=5)),
            ],
        ),
    ]
